# Generated by Django 6.0.1 on 2026-02-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ক্যাটেগরির নাম')),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
            ],
            options={
                'verbose_name': 'গ্যালারি ক্যাটেগরি',
                'verbose_name_plural': 'গ্যালারি ক্যাটেগরিসমূহ',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ছবি')),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
                ('date_taken', models.DateField(verbose_name='তোলার তারিখ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='প্রধান পাতায় দেখান')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycategory', verbose_name='ক্যাটেগরি')),
            ],
            options={
                'verbose_name': 'গ্যালারি ছবি',
                'verbose_name_plural': 'গ্যালারি ছবিসমূহ',
            },
        ),
    ]
