# Generated by Django 6.0.1 on 2026-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন')),
                ('subject', models.CharField(max_length=200, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='প্রেরণের তারিখ')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'verbose_name_plural': 'যোগাযোগ বার্তাসমূহ',
            },
        ),
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='প্রতিষ্ঠানের নাম')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('history', models.TextField(verbose_name='ইতিহাস')),
                ('mission', models.TextField(verbose_name='মিশন')),
                ('vision', models.TextField(verbose_name='ভিশন')),
                ('established_date', models.DateField(verbose_name='প্রতিষ্ঠার তারিখ')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
            ],
            options={
                'verbose_name': 'প্রতিষ্ঠানের তথ্য',
                'verbose_name_plural': 'প্রতিষ্ঠানের তথ্য',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের তারিখ')),
                ('valid_until', models.DateField(verbose_name='বৈধতা তারিখ')),
                ('is_important', models.BooleanField(default=False, verbose_name='গুরুত্বপূর্ণ')),
                ('file', models.FileField(blank=True, upload_to='notices/', verbose_name='ফাইল')),
            ],
            options={
                'verbose_name': 'নোটিশ',
                'verbose_name_plural': 'নোটিশসমূহ',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='প্রোগ্রামের নাম')),
                ('program_type', models.CharField(choices=[('হিফজ', 'হিফজুল কুরআন'), ('নাযেরা', 'নাযেরা কোর্স'), ('তাকমীল', 'তাকমীল (ফাজিল)'), ('মুতাওয়াসসিতাহ', 'মুতাওয়াসসিতাহ'), ('সানাবিয়া', 'সানাবিয়া উলুম'), ('ইফতা', 'ইফতা কোর্স'), ('দাওরাহ', 'দাওরাহে হাদিস')], max_length=50, verbose_name='ধরণ')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('duration', models.CharField(max_length=50, verbose_name='সময়কাল')),
                ('eligibility', models.TextField(verbose_name='যোগ্যতা')),
                ('total_seats', models.IntegerField(default=50, verbose_name='মোট আসন')),
                ('is_active', models.BooleanField(default=True, verbose_name='চালু আছে')),
            ],
            options={
                'verbose_name': 'একাডেমিক প্রোগ্রাম',
                'verbose_name_plural': 'একাডেমিক প্রোগ্রাম',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('designation', models.CharField(max_length=100, verbose_name='পদবী')),
                ('qualifications', models.TextField(verbose_name='শিক্ষাগত যোগ্যতা')),
                ('experience', models.TextField(verbose_name='অভিজ্ঞতা')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='ফোন')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='ছবি')),
                ('joining_date', models.DateField(verbose_name='যোগদানের তারিখ')),
                ('is_active', models.BooleanField(default=True, verbose_name='বর্তমান')),
            ],
            options={
                'verbose_name': 'শিক্ষক',
                'verbose_name_plural': 'শিক্ষকবৃন্দ',
            },
        ),
    ]
