# Generated by Django 5.1.3 on 2026-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("ইফতা", "ইফতা কোর্স"),
                    ("নাযেরা", "নাযেরা কোর্স"),
                    ("হিফজ", "হিফজুল কুরআন"),
                    ("দরসে নেযামি", "কিতাব বিভাগ"),
                ],
                max_length=50,
                verbose_name="ধরণ",
            ),
        ),
    ]
