# Generated by Django 6.0.1 on 2026-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ইভেন্টের নাম')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('event_date', models.DateField(verbose_name='ইভেন্ট তারিখ')),
                ('event_time', models.TimeField(verbose_name='সময়')),
                ('venue', models.CharField(max_length=200, verbose_name='স্থান')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'ইভেন্ট',
                'verbose_name_plural': 'ইভেন্টসমূহ',
            },
        ),
    ]
